# x-archived-from: amazon-codebuild-x-amz-target-codebuild-20161006-updateprojectvisibility-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2016-10-06'
  x-release: v4
  title: 'AWS CodeBuild #X Amz Target=CodeBuild…'
  description: 'CodeBuild

    CodeBuild is a fully managed build service in the cloud.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codebuild
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codebuild-2016-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: https://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: http://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
- url: https://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeBuild 20161006.UpdateProjectVisibility'
paths:
  /#X-Amz-Target=CodeBuild_20161006.UpdateProjectVisibility:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UpdateProjectVisibility
      description: 'Changes the public visibility for a project. The project''s build results, logs, and artifacts are available to the general public. For more information, see Public build projects in the CodeBuild User Guide.


        The following should be kept in mind when making your projects public:


        All of a project''s build results, logs, and artifacts, including builds that were run when the project was private, are available to the general public.


        All build logs and artifacts are available to the public. Environment variables, source code, and other sensitive information may have been output to the build logs and artifacts. You must be careful about what information is output to the build logs. Some best practice are:


        Do not store sensitive values, especially Amazon Web Services access key IDs and secret access keys, in environment variables. We recommend that you use an Amazon EC2 Systems Manager Parameter Store or Secrets Manager to store sensitive values.


        Follow Best practices for using webhooks in the CodeBuild User Guide to limit which entities can trigger a build, and do not store the buildspec in the project itself, to ensure that your webhooks are as secure as possible.


        A malicious user can use public builds to distribute malicious artifacts. We recommend that you review all pull requests to verify that the pull request is a legitimate change. We also recommend that you validate any artifacts with their checksums to make sure that the correct artifacts are being downloaded.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProjectVisibilityOutput'
              examples:
                UpdateProjectVisibility200Example:
                  summary: Default UpdateProjectVisibility 200 response
                  x-microcks-default: true
                  value:
                    projectArn: arn:aws:service:us-east-1:123456789012:resource/example
                    publicProjectAlias: example-value
                    projectVisibility: PUBLIC_READ
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                UpdateProjectVisibility480Example:
                  summary: Default UpdateProjectVisibility 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                UpdateProjectVisibility481Example:
                  summary: Default UpdateProjectVisibility 481 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectVisibilityInput'
            examples:
              UpdateProjectVisibilityRequestExample:
                summary: Default UpdateProjectVisibility request
                x-microcks-default: true
                value:
                  projectArn: arn:aws:service:us-east-1:123456789012:resource/example
                  projectVisibility: PUBLIC_READ
                  resourceAccessRole: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeBuild_20161006.UpdateProjectVisibility
      summary: Amazon CodeBuild Update Project Visibility
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeBuild 20161006.UpdateProjectVisibility'
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    UpdateProjectVisibilityOutput:
      type: object
      properties:
        projectArn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The Amazon Resource Name (ARN) of the build project.
        publicProjectAlias:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: 'Contains the project identifier used with the public build APIs. '
        projectVisibility:
          $ref: '#/components/schemas/ProjectVisibilityType'
    NonEmptyString:
      type: string
      minLength: 1
    InvalidInputException: {}
    ResourceNotFoundException: {}
    ProjectVisibilityType:
      type: string
      enum:
      - PUBLIC_READ
      - PRIVATE
      description: <p>Specifies the visibility of the project's builds. Possible values are:</p> <dl> <dt>PUBLIC_READ</dt> <dd> <p>The project builds are visible to the public.</p> </dd> <dt>PRIVATE</dt> <dd> <p>The project builds are not visible to the public.</p> </dd> </dl>
    UpdateProjectVisibilityInput:
      type: object
      required:
      - projectArn
      - projectVisibility
      title: UpdateProjectVisibilityInput
      properties:
        projectArn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The Amazon Resource Name (ARN) of the build project.
        projectVisibility:
          $ref: '#/components/schemas/ProjectVisibilityType'
        resourceAccessRole:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The ARN of the IAM role that enables CodeBuild to access the CloudWatch Logs and Amazon S3 artifacts for the project's builds.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codebuild/
x-hasEquivalentPaths: true
