# x-archived-from: amazon-codebuild-x-amz-target-codebuild-20161006-describecodecoverages-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2016-10-06'
  x-release: v4
  title: 'AWS CodeBuild #X Amz Target=CodeBuild…'
  description: 'CodeBuild

    CodeBuild is a fully managed build service in the cloud.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codebuild
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codebuild-2016-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: https://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: http://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
- url: https://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeBuild 20161006.DescribeCodeCoverages'
paths:
  /#X-Amz-Target=CodeBuild_20161006.DescribeCodeCoverages:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeCodeCoverages
      description: Retrieves one or more code coverage reports.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeCodeCoveragesOutput'
              examples:
                DescribeCodeCoverages200Example:
                  summary: Default DescribeCodeCoverages 200 response
                  x-microcks-default: true
                  value:
                    nextToken: example-value
                    codeCoverages: example-value
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                DescribeCodeCoverages480Example:
                  summary: Default DescribeCodeCoverages 480 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeCodeCoveragesInput'
            examples:
              DescribeCodeCoveragesRequestExample:
                summary: Default DescribeCodeCoverages request
                x-microcks-default: true
                value:
                  reportArn: arn:aws:service:us-east-1:123456789012:resource/example
                  nextToken: example-value
                  maxResults: example-value
                  sortOrder: example-value
                  sortBy: example-value
                  minLineCoveragePercentage: example-value
                  maxLineCoveragePercentage: example-value
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeBuild_20161006.DescribeCodeCoverages
      summary: Amazon CodeBuild Describe Code Coverages
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeBuild 20161006.DescribeCodeCoverages'
components:
  schemas:
    DescribeCodeCoveragesOutput:
      type: object
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: If there are more items to return, this contains a token that is passed to a subsequent call to <code>DescribeCodeCoverages</code> to retrieve the next set of items.
        codeCoverages:
          allOf:
          - $ref: '#/components/schemas/CodeCoverages'
          - description: An array of <code>CodeCoverage</code> objects that contain the results.
    SortOrderType:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    NonEmptyString:
      type: string
      minLength: 1
    Timestamp:
      type: string
      format: date-time
    DescribeCodeCoveragesInput:
      type: object
      required:
      - reportArn
      title: DescribeCodeCoveragesInput
      properties:
        reportArn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The ARN of the report for which test cases are returned. '
        nextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The <code>nextToken</code> value returned from a previous call to <code>DescribeCodeCoverages</code>. This specifies the next item to return. To return the beginning of the list, exclude this parameter.
        maxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: The maximum number of results to return.
        sortOrder:
          allOf:
          - $ref: '#/components/schemas/SortOrderType'
          - description: Specifies if the results are sorted in ascending or descending order.
        sortBy:
          allOf:
          - $ref: '#/components/schemas/ReportCodeCoverageSortByType'
          - description: <p>Specifies how the results are sorted. Possible values are:</p> <dl> <dt>FILE_PATH</dt> <dd> <p>The results are sorted by file path.</p> </dd> <dt>LINE_COVERAGE_PERCENTAGE</dt> <dd> <p>The results are sorted by the percentage of lines that are covered.</p> </dd> </dl>
        minLineCoveragePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The minimum line coverage percentage to report.
        maxLineCoveragePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The maximum line coverage percentage to report.
    PageSize:
      type: integer
      minimum: 1
      maximum: 100
    NonNegativeInt:
      type: integer
      minimum: 0
    InvalidInputException: {}
    String:
      type: string
    CodeCoverages:
      type: array
      items:
        $ref: '#/components/schemas/CodeCoverage'
    CodeCoverage:
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The identifier of the code coverage report.
        reportARN:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The ARN of the report.
        filePath:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The path of the test report file.
        lineCoveragePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of lines that are covered by your tests.
        linesCovered:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of lines that are covered by your tests.
        linesMissed:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of lines that are not covered by your tests.
        branchCoveragePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of branches that are covered by your tests.
        branchesCovered:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of conditional branches that are covered by your tests.
        branchesMissed:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of conditional branches that are not covered by your tests.
        expired:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time that the tests were run.
      description: <p>Contains code coverage report information.</p> <p>Line coverage measures how many statements your tests cover. A statement is a single instruction, not including comments, conditionals, etc.</p> <p>Branch coverage determines if your tests cover every possible branch of a control structure, such as an <code>if</code> or <code>case</code> statement.</p>
    Percentage:
      type: number
      format: double
      minimum: 0
      maximum: 100
    ReportCodeCoverageSortByType:
      type: string
      enum:
      - LINE_COVERAGE_PERCENTAGE
      - FILE_PATH
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codebuild/
x-hasEquivalentPaths: true
