# x-archived-from: amazon-codebuild-x-amz-target-codebuild-20161006-listbuildbatchesforproject-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2016-10-06'
  x-release: v4
  title: 'AWS CodeBuild #X Amz Target=CodeBuild…'
  description: 'CodeBuild

    CodeBuild is a fully managed build service in the cloud.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codebuild
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codebuild-2016-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: https://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: http://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
- url: https://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeBuild 20161006.ListBuildBatchesForProject'
paths:
  /#X-Amz-Target=CodeBuild_20161006.ListBuildBatchesForProject:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListBuildBatchesForProject
      description: Retrieves the identifiers of the build batches for a specific project.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBuildBatchesForProjectOutput'
              examples:
                ListBuildBatchesForProject200Example:
                  summary: Default ListBuildBatchesForProject 200 response
                  x-microcks-default: true
                  value:
                    ids: '500123'
                    nextToken: example-value
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                ListBuildBatchesForProject480Example:
                  summary: Default ListBuildBatchesForProject 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                ListBuildBatchesForProject481Example:
                  summary: Default ListBuildBatchesForProject 481 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListBuildBatchesForProjectInput'
            examples:
              ListBuildBatchesForProjectRequestExample:
                summary: Default ListBuildBatchesForProject request
                x-microcks-default: true
                value:
                  projectName: example-resource
                  filter: example-value
                  maxResults: example-value
                  sortOrder: example-value
                  nextToken: example-value
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeBuild_20161006.ListBuildBatchesForProject
      summary: Amazon CodeBuild List Build Batches for Project
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeBuild 20161006.ListBuildBatchesForProject'
components:
  schemas:
    String:
      type: string
    ListBuildBatchesForProjectInput:
      type: object
      title: ListBuildBatchesForProjectInput
      properties:
        projectName:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: The name of the project.
        filter:
          allOf:
          - $ref: '#/components/schemas/BuildBatchFilter'
          - description: A <code>BuildBatchFilter</code> object that specifies the filters for the search.
        maxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: The maximum number of results to return.
        sortOrder:
          allOf:
          - $ref: '#/components/schemas/SortOrderType'
          - description: '<p>Specifies the sort order of the returned items. Valid values include:</p> <ul> <li> <p> <code>ASCENDING</code>: List the batch build identifiers in ascending order by identifier.</p> </li> <li> <p> <code>DESCENDING</code>: List the batch build identifiers in descending order by identifier.</p> </li> </ul>'
        nextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The <code>nextToken</code> value returned from a previous call to <code>ListBuildBatchesForProject</code>. This specifies the next item to return. To return the beginning of the list, exclude this parameter.
    SortOrderType:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    StatusType:
      type: string
      enum:
      - SUCCEEDED
      - FAILED
      - FAULT
      - TIMED_OUT
      - IN_PROGRESS
      - STOPPED
    BuildBatchIds:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
      minItems: 0
      maxItems: 100
    PageSize:
      type: integer
      minimum: 1
      maximum: 100
    NonEmptyString:
      type: string
      minLength: 1
    InvalidInputException: {}
    ListBuildBatchesForProjectOutput:
      type: object
      properties:
        ids:
          allOf:
          - $ref: '#/components/schemas/BuildBatchIds'
          - description: An array of strings that contains the batch build identifiers.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: If there are more items to return, this contains a token that is passed to a subsequent call to <code>ListBuildBatchesForProject</code> to retrieve the next set of items.
    ResourceNotFoundException: {}
    BuildBatchFilter:
      type: object
      properties:
        status:
          allOf:
          - $ref: '#/components/schemas/StatusType'
          - description: The status of the batch builds to retrieve. Only batch builds that have this status will be retrieved.
      description: Specifies filters when retrieving batch builds.
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codebuild/
x-hasEquivalentPaths: true
