# x-archived-from: amazon-codebuild-x-amz-target-codebuild-20161006-updatereportgroup-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2016-10-06'
  x-release: v4
  title: 'AWS CodeBuild #X Amz Target=CodeBuild…'
  description: 'CodeBuild

    CodeBuild is a fully managed build service in the cloud.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codebuild
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codebuild-2016-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: https://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: http://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
- url: https://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeBuild 20161006.UpdateReportGroup'
paths:
  /#X-Amz-Target=CodeBuild_20161006.UpdateReportGroup:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UpdateReportGroup
      description: Updates a report group.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateReportGroupOutput'
              examples:
                UpdateReportGroup200Example:
                  summary: Default UpdateReportGroup 200 response
                  x-microcks-default: true
                  value:
                    reportGroup: example-value
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                UpdateReportGroup480Example:
                  summary: Default UpdateReportGroup 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                UpdateReportGroup481Example:
                  summary: Default UpdateReportGroup 481 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReportGroupInput'
            examples:
              UpdateReportGroupRequestExample:
                summary: Default UpdateReportGroup request
                x-microcks-default: true
                value:
                  arn: arn:aws:service:us-east-1:123456789012:resource/example
                  exportConfig: example-value
                  tags: example-value
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeBuild_20161006.UpdateReportGroup
      summary: Amazon CodeBuild Update Report Group
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeBuild 20161006.UpdateReportGroup'
components:
  schemas:
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      minItems: 0
      maxItems: 50
    KeyInput:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=@+\-]*)$
      minLength: 1
      maxLength: 127
    UpdateReportGroupInput:
      type: object
      required:
      - arn
      title: UpdateReportGroupInput
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The ARN of the report group to update. '
        exportConfig:
          allOf:
          - $ref: '#/components/schemas/ReportExportConfig'
          - description: '<p> Used to specify an updated export type. Valid values are: </p> <ul> <li> <p> <code>S3</code>: The report results are exported to an S3 bucket. </p> </li> <li> <p> <code>NO_EXPORT</code>: The report results are not exported. </p> </li> </ul>'
        tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: <p> An updated list of tag key and value pairs associated with this report group. </p> <p>These tags are available for use by Amazon Web Services services that support CodeBuild report group tags.</p>
    NonEmptyString:
      type: string
      minLength: 1
    ResourceNotFoundException: {}
    Timestamp:
      type: string
      format: date-time
    ReportExportConfig:
      type: object
      properties:
        exportConfigType:
          allOf:
          - $ref: '#/components/schemas/ReportExportConfigType'
          - description: '<p> The export configuration type. Valid values are: </p> <ul> <li> <p> <code>S3</code>: The report results are exported to an S3 bucket. </p> </li> <li> <p> <code>NO_EXPORT</code>: The report results are not exported. </p> </li> </ul>'
        s3Destination:
          allOf:
          - $ref: '#/components/schemas/S3ReportExportConfig'
          - description: ' A <code>S3ReportExportConfig</code> object that contains information about the S3 bucket where the run of a report is exported. '
      description: ' Information about the location where the run of a report is exported. '
    S3ReportExportConfig:
      type: object
      properties:
        bucket:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The name of the S3 bucket where the raw data of a report are exported. '
        bucketOwner:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services account identifier of the owner of the Amazon S3 bucket. This allows report data to be exported to an Amazon S3 bucket that is owned by an account other than the account running the build.
        path:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' The path to the exported report''s raw data results. '
        packaging:
          allOf:
          - $ref: '#/components/schemas/ReportPackagingType'
          - description: '<p> The type of build output artifact to create. Valid values include: </p> <ul> <li> <p> <code>NONE</code>: CodeBuild creates the raw data in the output bucket. This is the default if packaging is not specified. </p> </li> <li> <p> <code>ZIP</code>: CodeBuild creates a ZIP file with the raw data in the output bucket. </p> </li> </ul>'
        encryptionKey:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The encryption key for the report''s encrypted raw data. '
        encryptionDisabled:
          allOf:
          - $ref: '#/components/schemas/WrapperBoolean'
          - description: ' A boolean value that specifies if the results of a report are encrypted. '
      description: ' Information about the S3 bucket where the raw data of a report are exported. '
    ReportGroup:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: 'The ARN of the <code>ReportGroup</code>. '
        name:
          allOf:
          - $ref: '#/components/schemas/ReportGroupName'
          - description: 'The name of the <code>ReportGroup</code>. '
        type:
          allOf:
          - $ref: '#/components/schemas/ReportType'
          - description: <p>The type of the <code>ReportGroup</code>. This can be one of the following values:</p> <dl> <dt>CODE_COVERAGE</dt> <dd> <p>The report group contains code coverage reports.</p> </dd> <dt>TEST</dt> <dd> <p>The report group contains test reports.</p> </dd> </dl>
        exportConfig:
          allOf:
          - $ref: '#/components/schemas/ReportExportConfig'
          - description: 'Information about the destination where the raw data of this <code>ReportGroup</code> is exported. '
        created:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: 'The date and time this <code>ReportGroup</code> was created. '
        lastModified:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: 'The date and time this <code>ReportGroup</code> was last modified. '
        tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: <p>A list of tag key and value pairs associated with this report group. </p> <p>These tags are available for use by Amazon Web Services services that support CodeBuild report group tags.</p>
        status:
          allOf:
          - $ref: '#/components/schemas/ReportGroupStatusType'
          - description: <p>The status of the report group. This property is read-only.</p> <p>This can be one of the following values:</p> <dl> <dt>ACTIVE</dt> <dd> <p>The report group is active.</p> </dd> <dt>DELETING</dt> <dd> <p>The report group is in the process of being deleted.</p> </dd> </dl>
      description: 'A series of reports. Each report contains information about the results from running a series of test cases. You specify the test cases for a report group in the buildspec for a build project using one or more paths to the test case files. '
    ReportPackagingType:
      type: string
      enum:
      - ZIP
      - NONE
    ReportType:
      type: string
      enum:
      - TEST
      - CODE_COVERAGE
    ReportGroupName:
      type: string
      minLength: 2
      maxLength: 128
    WrapperBoolean:
      type: boolean
    ReportExportConfigType:
      type: string
      enum:
      - S3
      - NO_EXPORT
    Tag:
      type: object
      properties:
        key:
          allOf:
          - $ref: '#/components/schemas/KeyInput'
          - description: The tag's key.
        value:
          allOf:
          - $ref: '#/components/schemas/ValueInput'
          - description: The tag's value.
      description: <p>A tag, consisting of a key and a value.</p> <p>This tag is available for use by Amazon Web Services services that support tags in CodeBuild.</p>
    InvalidInputException: {}
    ValueInput:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=@+\-]*)$
      minLength: 0
      maxLength: 255
    String:
      type: string
    UpdateReportGroupOutput:
      type: object
      properties:
        reportGroup:
          allOf:
          - $ref: '#/components/schemas/ReportGroup'
          - description: ' Information about the updated report group. '
    ReportGroupStatusType:
      type: string
      enum:
      - ACTIVE
      - DELETING
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codebuild/
x-hasEquivalentPaths: true
