# x-archived-from: amazon-codebuild-x-amz-target-codebuild-20161006-batchgetreports-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2016-10-06'
  x-release: v4
  title: 'AWS CodeBuild #X Amz Target=CodeBuild…'
  description: 'CodeBuild

    CodeBuild is a fully managed build service in the cloud.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: codebuild
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/codebuild-2016-10-06.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: https://codebuild.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS CodeBuild multi-region endpoint
- url: http://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
- url: https://codebuild.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS CodeBuild endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=CodeBuild 20161006.BatchGetReports'
paths:
  /#X-Amz-Target=CodeBuild_20161006.BatchGetReports:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: BatchGetReports
      description: Returns an array of reports.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchGetReportsOutput'
              examples:
                BatchGetReports200Example:
                  summary: Default BatchGetReports 200 response
                  x-microcks-default: true
                  value:
                    reports: example-value
                    reportsNotFound: example-value
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                BatchGetReports480Example:
                  summary: Default BatchGetReports 480 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchGetReportsInput'
            examples:
              BatchGetReportsRequestExample:
                summary: Default BatchGetReports request
                x-microcks-default: true
                value:
                  reportArns: arn:aws:service:us-east-1:123456789012:resource/example
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - CodeBuild_20161006.BatchGetReports
      summary: Amazon CodeBuild Batch Get Reports
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=CodeBuild 20161006.BatchGetReports'
components:
  schemas:
    WrapperLong:
      type: integer
    NonEmptyString:
      type: string
      minLength: 1
    Timestamp:
      type: string
      format: date-time
    ReportExportConfig:
      type: object
      properties:
        exportConfigType:
          allOf:
          - $ref: '#/components/schemas/ReportExportConfigType'
          - description: '<p> The export configuration type. Valid values are: </p> <ul> <li> <p> <code>S3</code>: The report results are exported to an S3 bucket. </p> </li> <li> <p> <code>NO_EXPORT</code>: The report results are not exported. </p> </li> </ul>'
        s3Destination:
          allOf:
          - $ref: '#/components/schemas/S3ReportExportConfig'
          - description: ' A <code>S3ReportExportConfig</code> object that contains information about the S3 bucket where the run of a report is exported. '
      description: ' Information about the location where the run of a report is exported. '
    S3ReportExportConfig:
      type: object
      properties:
        bucket:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The name of the S3 bucket where the raw data of a report are exported. '
        bucketOwner:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services account identifier of the owner of the Amazon S3 bucket. This allows report data to be exported to an Amazon S3 bucket that is owned by an account other than the account running the build.
        path:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' The path to the exported report''s raw data results. '
        packaging:
          allOf:
          - $ref: '#/components/schemas/ReportPackagingType'
          - description: '<p> The type of build output artifact to create. Valid values include: </p> <ul> <li> <p> <code>NONE</code>: CodeBuild creates the raw data in the output bucket. This is the default if packaging is not specified. </p> </li> <li> <p> <code>ZIP</code>: CodeBuild creates a ZIP file with the raw data in the output bucket. </p> </li> </ul>'
        encryptionKey:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The encryption key for the report''s encrypted raw data. '
        encryptionDisabled:
          allOf:
          - $ref: '#/components/schemas/WrapperBoolean'
          - description: ' A boolean value that specifies if the results of a report are encrypted. '
      description: ' Information about the S3 bucket where the raw data of a report are exported. '
    ReportPackagingType:
      type: string
      enum:
      - ZIP
      - NONE
    ReportType:
      type: string
      enum:
      - TEST
      - CODE_COVERAGE
    ReportArns:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
      minItems: 1
      maxItems: 100
    ReportStatusType:
      type: string
      enum:
      - GENERATING
      - SUCCEEDED
      - FAILED
      - INCOMPLETE
      - DELETING
    WrapperBoolean:
      type: boolean
    CodeCoverageReportSummary:
      type: object
      properties:
        lineCoveragePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of lines that are covered by your tests.
        linesCovered:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of lines that are covered by your tests.
        linesMissed:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of lines that are not covered by your tests.
        branchCoveragePercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of branches that are covered by your tests.
        branchesCovered:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of conditional branches that are covered by your tests.
        branchesMissed:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInt'
          - description: The number of conditional branches that are not covered by your tests.
      description: <p>Contains a summary of a code coverage report.</p> <p>Line coverage measures how many statements your tests cover. A statement is a single instruction, not including comments, conditionals, etc.</p> <p>Branch coverage determines if your tests cover every possible branch of a control structure, such as an <code>if</code> or <code>case</code> statement.</p>
    ReportStatusCounts:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/WrapperInt'
    ReportExportConfigType:
      type: string
      enum:
      - S3
      - NO_EXPORT
    Report:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The ARN of the report run. '
        type:
          allOf:
          - $ref: '#/components/schemas/ReportType'
          - description: <p>The type of the report that was run.</p> <dl> <dt>CODE_COVERAGE</dt> <dd> <p>A code coverage report.</p> </dd> <dt>TEST</dt> <dd> <p>A test report.</p> </dd> </dl>
        name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' The name of the report that was run. '
        reportGroupArn:
          allOf:
          - $ref: '#/components/schemas/NonEmptyString'
          - description: ' The ARN of the report group associated with this report. '
        executionId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: ' The ARN of the build run that generated this report. '
        status:
          allOf:
          - $ref: '#/components/schemas/ReportStatusType'
          - description: ' The status of this report. '
        created:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: ' The date and time this report run occurred. '
        expired:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: ' The date and time a report expires. A report expires 30 days after it is created. An expired report is not available to view in CodeBuild. '
        exportConfig:
          allOf:
          - $ref: '#/components/schemas/ReportExportConfig'
          - description: ' Information about where the raw data used to generate this report was exported. '
        truncated:
          allOf:
          - $ref: '#/components/schemas/WrapperBoolean'
          - description: ' A boolean that specifies if this report run is truncated. The list of test cases is truncated after the maximum number of test cases is reached. '
        testSummary:
          allOf:
          - $ref: '#/components/schemas/TestReportSummary'
          - description: ' A <code>TestReportSummary</code> object that contains information about this test report. '
        codeCoverageSummary:
          allOf:
          - $ref: '#/components/schemas/CodeCoverageReportSummary'
          - description: A <code>CodeCoverageReportSummary</code> object that contains a code coverage summary for this report.
      description: 'Information about the results from running a series of test cases during the run of a build project. The test cases are specified in the buildspec for the build project using one or more paths to the test case files. You can specify any type of tests you want, such as unit tests, integration tests, and functional tests. '
    BatchGetReportsInput:
      type: object
      required:
      - reportArns
      title: BatchGetReportsInput
      properties:
        reportArns:
          allOf:
          - $ref: '#/components/schemas/ReportArns'
          - description: ' An array of ARNs that identify the <code>Report</code> objects to return. '
    InvalidInputException: {}
    NonNegativeInt:
      type: integer
      minimum: 0
    TestReportSummary:
      type: object
      required:
      - total
      - statusCounts
      - durationInNanoSeconds
      properties:
        total:
          allOf:
          - $ref: '#/components/schemas/WrapperInt'
          - description: ' The number of test cases in this <code>TestReportSummary</code>. The total includes truncated test cases. '
        statusCounts:
          allOf:
          - $ref: '#/components/schemas/ReportStatusCounts'
          - description: ' A map that contains the number of each type of status returned by the test results in this <code>TestReportSummary</code>. '
        durationInNanoSeconds:
          allOf:
          - $ref: '#/components/schemas/WrapperLong'
          - description: ' The number of nanoseconds it took to run all of the test cases in this report. '
      description: ' Information about a test report. '
    String:
      type: string
    BatchGetReportsOutput:
      type: object
      properties:
        reports:
          allOf:
          - $ref: '#/components/schemas/Reports'
          - description: ' The array of <code>Report</code> objects returned by <code>BatchGetReports</code>. '
        reportsNotFound:
          allOf:
          - $ref: '#/components/schemas/ReportArns'
          - description: ' An array of ARNs passed to <code>BatchGetReportGroups</code> that are not associated with a <code>Report</code>. '
    WrapperInt:
      type: integer
    Reports:
      type: array
      items:
        $ref: '#/components/schemas/Report'
      minItems: 1
      maxItems: 100
    Percentage:
      type: number
      format: double
      minimum: 0
      maximum: 100
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/codebuild/
x-hasEquivalentPaths: true
